name: Copr Build for CI

inputs:
  copr-user:
    description: The Copr user to build packages under
    required: true
  overlay:
    description: The rpm-gitoverlay overlay name to build (default is dnf-ci)
    default: dnf-ci

outputs:
  package-urls:
    description: The URLs of built RPM packages
    value: ${{steps.copr-build.outputs.package-urls}}

runs:
  using: "composite"
  steps:
    - name: Rebase the pull request on target branch
      shell: bash
      run: |
        REPO_NAME="${{github.event.repository.name}}"
        # if the triggering repo is ci-dnf-stack, the git we are rebasing is in the current directory
        # otherwise, it's cloned into the gits directory for rpm-overlay to build from
        if [ ${REPO_NAME} != "ci-dnf-stack" ]; then
          cd gits/${REPO_NAME}
        fi

        git config user.name github-actions
        git config user.email github-actions@github.com
        echo "Rebasing \"`git log --oneline -1`\" on ${{github.event.pull_request.base.ref}}: \"`git log --oneline -1 origin/${{github.event.pull_request.base.ref}}`\""
        git rebase origin/${{github.event.pull_request.base.ref}}

    - name: Build packages in Copr
      id: copr-build
      shell: bash
      run: |
        PROJECT_NAME="CI-${{github.event.repository.name}}-pr${{github.event.pull_request.number}}"
        # if there's a git already cloned in the `gits` directory, rpm-gitoverlay will use it
        rpm-gitoverlay -o rpmlist --gitdir=gits build-overlay -s "overlays/${{inputs.overlay}}" rpm copr --owner "${{inputs.copr-user}}" --project "$PROJECT_NAME" --additional-repos="copr://rpmsoftwaremanagement/dnf-nightly" --chroot fedora-33-x86_64 --delete-project-after-days=7

        # delete the Copr secret just to be on the safe(er) side when running potentially untrusted PR code (albeit in a container, which should be secure)
        rm -rf "$HOME/.config/copr"

        # convert newlines to spaces (output variable assignment below doesn't support newlines)
        PACKAGE_URLS="$(tr '\n' ' ' < rpmlist)"
        echo "::set-output name=package-urls::$PACKAGE_URLS"
