# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  - job: tests
    trigger: pull_request
    identifier: "behave-dnf"
    targets:
      - fedora-all
    skip_build: true
    tmt_plan: "^/plans/integration/behave-dnf$"

  - job: tests
    trigger: pull_request
    identifier: "behave-dnf-bootc"
    targets:
      - fedora-all
    skip_build: true
    tmt_plan: "^/plans/integration/behave-dnf-bootc/"
