# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  - job: tests
    trigger: pull_request
    identifier: "createrepo_c-tests"
    targets:
      - fedora-all
      - fedora-eln
    skip_build: true
    tmt_plan: "^/plans/integration/behave-createrepo_c$"
