FROM fedora:23
MAINTAINER Jaroslav Mracek <jmracek@redhat.com>

ENV LANG en_US.utf8

RUN dnf -y --setopt=deltarpm=false upgrade rpm libsolv\
  && dnf -y --setopt=deltarpm=false --allowerasing install httpd python-behave python2-dnf dnf-plugins-core python-dnf-plugins-core python3-dnf-plugins-core {install_tito}

RUN dnf mark install python3-dnf python3-dnf-plugins-core

COPY repo /var/www/html/repo/

COPY initial_settings /initial_settings/

COPY features /behave/

{copy_local_file}

ADD httpd.conf /etc/httpd/conf/

ADD launch-test /usr/bin/

RUN mkdir -p /temp/dnf.repo

VOLUME /repo
