#!/bin/bash
set -xeuo pipefail

httpd -k start
vsftpd
new_name=${1}-${2}
mv /behave/${1}.feature /behave/${new_name}.feature
behave-2 -i $new_name -D dnf_cmd=$2 --junit --junit-directory /junit/ /behave/
