#!/bin/bash

PREFIXES="$@"

for file in $(find /tests -name *.feature -type f); do
    file_name=$(basename $file)
    old=${file_name%.*}
    for prefix in ${PREFIXES[@]}; do
        new=/behave/${old}-$prefix.feature
        cp ${file} ${new}
    done
done
behave-3 --dry-run --no-summary -f json /behave/
