#!/bin/bash
#
# the script modifies the test suite files so it can be run on different architectures
# Usage:
#  $ ./arch-switch
#  $ ./dnf-testing.sh build
#  $ ./dnf-testing.sh run

set -xe

PRIMARYARCH=`arch`

if [ "$PRIMARYARCH" == "x86_64" ]; then
  echo "No architecture changes needed for x86_64"
  exit 0
fi

# these secondary archs are mostly useless as packages built won't be installable anyway
# we need to skip test scenarios based on secondary architectures
[ "$PRIMARYARCH" == "ppc64le" ] && SECONDARYARCH=ppc
[ "$PRIMARYARCH" == "s390x" ] && SECONDARYARCH=s390
[ "$PRIMARYARCH" == "aarch64" ] && SECONDARYARCH=aarch

echo "Using $PRIMARYARCH, $SECONDARYARCH"

# substitution in testing files
sed -i "s/x86_64/$PRIMARYARCH/g" $( grep -l -R x86_64 fixtures dnf-behave-tests/features )
sed -i "s/i686/$SECONDARYARCH/g" $( grep -l -R i686 fixtures dnf-behave-tests/features )

echo "Done."
