#!/bin/bash
set -euo pipefail

RESERVE=0
TAGS=""
NAMES=()
FEATURE_PATH="/opt/behave"
FEATURE_FILE=""
DEFINES=""
DNFCOMMAND=""
JUNIT_SUBDIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -r|-R) RESERVE="$1"; shift;;
        -t|--tag|--tags) TAGS="$TAGS --tags $2"; shift 2;;
        -n) NAMES+=("-n" "$2"); shift 2;;
        --command) DNFCOMMAND="$2"; shift 2;;
        -D) DEFINES="$DEFINES -D $2"; shift 2;;
        -j) JUNIT_SUBDIR="$2"; shift 2;;
        *) FEATURE_FILE="$1"; shift;;
    esac
done

if [ ! -f "$FEATURE_PATH/$FEATURE_FILE" ]; then
    echo "Feature file not found: $FEATURE_PATH/$FEATURE_FILE" >&2
    exit 1
fi

if [ "$DNFCOMMAND" ]; then
    DEFINES="$DEFINES -D dnf_command=$DNFCOMMAND"
fi

if [ "$RESERVE" == "-r" ]; then
    # preserve all temporary directories
    DEFINES="$DEFINES -D preserve=1"
elif [ "$RESERVE" == "-R" ]; then
    # preserve temporary directories of failing tests
    DEFINES="$DEFINES -D preserve=f"
fi

TEST_EXIT=0
behave $DEFINES $TAGS "${NAMES[@]}" --no-skipped --junit --junit-directory="/junit/$JUNIT_SUBDIR" "$FEATURE_PATH/$FEATURE_FILE" || TEST_EXIT=$?

if [ "$RESERVE" == "-r" ] || [ "$RESERVE" == "-R" -a $TEST_EXIT -ne 0 ]; then
    bash || :
fi
exit $TEST_EXIT
