#!/bin/bash
set -xeuo pipefail

RESERVE=0
TAGS=""
FEATURE_PATH=""
DEFINES=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -r|-R) RESERVE="$1"; shift;;
        -t|--tag|--tags) TAGS="$TAGS --tags $2"; shift 2;;
        -D) DEFINES="$DEFINES -D $2"; shift 2;;
        *) FEATURE_PATH="$FEATURE_PATH /opt/behave/features/$1"; shift;;
    esac
done

if [ ! -f "$FEATURE_PATH" ]; then
    echo "Feature file not found: $FEATURE_PATH" >&2
    exit 1
fi


TEST_EXIT=0
behave $DEFINES $TAGS --junit --junit-directory=/junit/ "$FEATURE_PATH" || TEST_EXIT=$?

if [ "$RESERVE" == "-r" ] || [ "$RESERVE" == "-R" -a $TEST_EXIT -ne 0 ]; then
    bash || :
fi
exit $TEST_EXIT
