#!/bin/bash

export LANG=en_US

# define user-specific data for the config.userdata dictionary. Example: -D foo=bar to store it in config.userdata["foo"].
# -D NAME=VALUE, --define NAME=VALUE
ENV=""
ENV="$ENV -Ddnf_executable=dnf-3"

TAGS=""

# run only tier1 tests
#TAGS="$TAGS --tags @tier1"

# run only WIP tests
#TAGS="$TAGS --wip"

while [ "$1" != "" ]; do
    case "$1" in
        -t|--tag) TAGS="$TAGS --tags $2"; shift 2;;
        -w|--wip) TAGS="$TAGS --wip"; shift;;
        *) fatal "Non-implemented option: $1"
    esac
done

behave $ENV $TAGS features -v "$@"
