#!/bin/bash

export LANG=en_US.utf8
# having LC_TIME set to "cs_CZ.utf8" breaks random shell scenarios at the moment
export LC_TIME=en_US.utf8

# define user-specific data for the config.userdata dictionary. Example: -D foo=bar to store it in config.userdata["foo"].
# -D NAME=VALUE, --define NAME=VALUE
ENV=""
ENV="$ENV -Ddnf_executable=dnf-3"

TAGS=""

# run only tier1 tests
#TAGS="$TAGS --tags @tier1"

# run only WIP tests
#TAGS="$TAGS --wip"

behave $ENV $TAGS features -v "$@"
