#!/bin/bash

export LANG=en_US.utf8
# having LC_TIME set to "cs_CZ.utf8" breaks random shell scenarios at the moment
export LC_TIME=en_US.utf8

# define user-specific data for the config.userdata dictionary. Example: -D foo=bar to store it in config.userdata["foo"].
# -D NAME=VALUE, --define NAME=VALUE
ENV=""
ENV="$ENV -Ddnf_command=dnf-3"

TAGS=""

for opt in "$@"; do
  shift
  case $opt in
    -p|--preserve)
      ENV="$ENV -Dpreserve=yes"
      continue
      ;;
    -d|--destructive)
      ENV="$ENV -Ddestructive=yes"
      continue
      ;;
  esac
  set -- "$@" "$opt"
done

# run only tier1 tests
#TAGS="$TAGS --tags @tier1"

# run only WIP tests
#TAGS="$TAGS --wip"

behave $ENV $TAGS features -v "$@"
